export const GET_REVIEWS = "GET_REVIEWS";
export const NEW_REVIEW = "NEW_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const TOGGLE_REVIEW_RECOMMENDATION = "TOGGLE_REVIEW_RECOMMENDATION";
export const EDIT_REVIEW = "EDIT_REVIEW";
